spring.application.name=api
server.port=3001

spring.datasource.url=jdbc:postgresql://localhost:5434/mydb
spring.datasource.username=asela
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=86400000